"""更新PracticeSession模型加入session_feedbacks關係

Revision ID: 00409f80ca1d
Revises: b89c89a3dba7
Create Date: 2025-07-30 23:32:51.695393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00409f80ca1d'
down_revision: Union[str, None] = 'b89c89a3dba7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
