"""新增 AI 分析任務追蹤表和結果表

Revision ID: 204b799035bd
Revises: 00409f80ca1d
Create Date: 2025-08-13 18:46:10.584759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '204b799035bd'
down_revision: Union[str, None] = '00409f80ca1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_analysis_tasks',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('celery_task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('practice_session_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'SUCCESS', 'FAILURE', 'RETRY', name='taskstatus'), nullable=False),
    sa.Column('task_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('task_params', sa.JSON(), nullable=True),
    sa.Column('worker_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('current_step', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['practice_session_id'], ['practice_sessions.practice_session_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_ai_analysis_tasks_celery_task_id'), 'ai_analysis_tasks', ['celery_task_id'], unique=True)
    op.create_index(op.f('ix_ai_analysis_tasks_created_at'), 'ai_analysis_tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_analysis_tasks_practice_session_id'), 'ai_analysis_tasks', ['practice_session_id'], unique=False)
    op.create_index(op.f('ix_ai_analysis_tasks_status'), 'ai_analysis_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_ai_analysis_tasks_user_id'), 'ai_analysis_tasks', ['user_id'], unique=False)
    op.create_table('ai_analysis_results',
    sa.Column('result_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('analysis_result', sa.JSON(), nullable=False),
    sa.Column('analysis_model_version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('processing_time_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['ai_analysis_tasks.task_id'], ),
    sa.PrimaryKeyConstraint('result_id')
    )
    op.create_index(op.f('ix_ai_analysis_results_created_at'), 'ai_analysis_results', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_analysis_results_task_id'), 'ai_analysis_results', ['task_id'], unique=True)
    op.add_column('practice_sessions', sa.Column('ai_task_id', sa.Uuid(), nullable=True))
    op.add_column('practice_sessions', sa.Column('ai_analysis_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.create_foreign_key(None, 'practice_sessions', 'ai_analysis_tasks', ['ai_task_id'], ['task_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'practice_sessions', type_='foreignkey')
    op.drop_column('practice_sessions', 'ai_analysis_status')
    op.drop_column('practice_sessions', 'ai_task_id')
    op.drop_index(op.f('ix_ai_analysis_results_task_id'), table_name='ai_analysis_results')
    op.drop_index(op.f('ix_ai_analysis_results_created_at'), table_name='ai_analysis_results')
    op.drop_table('ai_analysis_results')
    op.drop_index(op.f('ix_ai_analysis_tasks_user_id'), table_name='ai_analysis_tasks')
    op.drop_index(op.f('ix_ai_analysis_tasks_status'), table_name='ai_analysis_tasks')
    op.drop_index(op.f('ix_ai_analysis_tasks_practice_session_id'), table_name='ai_analysis_tasks')
    op.drop_index(op.f('ix_ai_analysis_tasks_created_at'), table_name='ai_analysis_tasks')
    op.drop_index(op.f('ix_ai_analysis_tasks_celery_task_id'), table_name='ai_analysis_tasks')
    op.drop_table('ai_analysis_tasks')
    # ### end Alembic commands ###
