"""修改AI分析任務為以practice_record為基礎

Revision ID: 50cb4f7496f0
Revises: 204b799035bd
Create Date: 2025-08-14 03:17:23.101477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '50cb4f7496f0'
down_revision: Union[str, None] = '204b799035bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_analysis_results', 'analysis_result',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.add_column('ai_analysis_tasks', sa.Column('practice_record_id', sa.Uuid(), nullable=False))
    op.drop_index(op.f('ix_ai_analysis_tasks_practice_session_id'), table_name='ai_analysis_tasks')
    op.create_index(op.f('ix_ai_analysis_tasks_practice_record_id'), 'ai_analysis_tasks', ['practice_record_id'], unique=False)
    op.drop_constraint(op.f('fk_ai_analysis_tasks_practice_session_id_practice_sessions'), 'ai_analysis_tasks', type_='foreignkey')
    op.create_foreign_key(None, 'ai_analysis_tasks', 'practice_records', ['practice_record_id'], ['practice_record_id'])
    op.drop_column('ai_analysis_tasks', 'practice_session_id')
    op.add_column('practice_records', sa.Column('ai_task_id', sa.Uuid(), nullable=True))
    op.add_column('practice_records', sa.Column('ai_analysis_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.create_foreign_key(None, 'practice_records', 'ai_analysis_tasks', ['ai_task_id'], ['task_id'])
    op.drop_constraint(op.f('fk_practice_sessions_ai_task_id_ai_analysis_tasks'), 'practice_sessions', type_='foreignkey')
    op.drop_column('practice_sessions', 'ai_analysis_status')
    op.drop_column('practice_sessions', 'ai_task_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practice_sessions', sa.Column('ai_task_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('practice_sessions', sa.Column('ai_analysis_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_practice_sessions_ai_task_id_ai_analysis_tasks'), 'practice_sessions', 'ai_analysis_tasks', ['ai_task_id'], ['task_id'])
    op.drop_constraint(None, 'practice_records', type_='foreignkey')
    op.drop_column('practice_records', 'ai_analysis_status')
    op.drop_column('practice_records', 'ai_task_id')
    op.add_column('ai_analysis_tasks', sa.Column('practice_session_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ai_analysis_tasks', type_='foreignkey')
    op.create_foreign_key(op.f('fk_ai_analysis_tasks_practice_session_id_practice_sessions'), 'ai_analysis_tasks', 'practice_sessions', ['practice_session_id'], ['practice_session_id'])
    op.drop_index(op.f('ix_ai_analysis_tasks_practice_record_id'), table_name='ai_analysis_tasks')
    op.create_index(op.f('ix_ai_analysis_tasks_practice_session_id'), 'ai_analysis_tasks', ['practice_session_id'], unique=False)
    op.drop_column('ai_analysis_tasks', 'practice_record_id')
    op.alter_column('ai_analysis_results', 'analysis_result',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###
