"""Add therapist application and document tables

Revision ID: 667cb2f3aef3
Revises: c74b06f80000
Create Date: 2025-06-28 17:30:00.008933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '667cb2f3aef3'
down_revision: Union[str, None] = 'c74b06f80000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('therapistapplication',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTION_REQUIRED', 'APPROVED', 'REJECTED', name='applicationstatus'), nullable=False),
    sa.Column('rejection_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reviewed_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_therapistapplication_user_id'), 'therapistapplication', ['user_id'], unique=False)
    op.create_table('uploadeddocument',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('document_type', sa.Enum('ID_CARD_FRONT', 'ID_CARD_BACK', 'THERAPIST_CERTIFICATE', name='documenttype'), nullable=False),
    sa.Column('file_object_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['therapistapplication.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploadeddocument_file_object_name'), 'uploadeddocument', ['file_object_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploadeddocument_file_object_name'), table_name='uploadeddocument')
    op.drop_table('uploadeddocument')
    op.drop_index(op.f('ix_therapistapplication_user_id'), table_name='therapistapplication')
    op.drop_table('therapistapplication')
    # ### end Alembic commands ###
