"""Add verification_application_id to TherapistProfile

Revision ID: 775631cb8e1e
Revises: 667cb2f3aef3
Create Date: 2025-07-01 22:43:08.033151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '775631cb8e1e'
down_revision: Union[str, None] = '667cb2f3aef3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('therapist_profiles', sa.Column('verification_application_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'therapist_profiles', 'therapistapplication', ['verification_application_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'therapist_profiles', type_='foreignkey')
    op.drop_column('therapist_profiles', 'verification_application_id')
    # ### end Alembic commands ###
