"""加入新表_練習會話自己的回饋表

Revision ID: b89c89a3dba7
Revises: 9a7b581ee2c3
Create Date: 2025-07-30 23:24:46.255977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b89c89a3dba7'
down_revision: Union[str, None] = '9a7b581ee2c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practice_session_feedbacks',
    sa.Column('session_feedback_id', sa.Uuid(), nullable=False),
    sa.Column('practice_session_id', sa.Uuid(), nullable=False),
    sa.Column('therapist_id', sa.Uuid(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['practice_session_id'], ['practice_sessions.practice_session_id'], ),
    sa.ForeignKeyConstraint(['therapist_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('session_feedback_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('practice_session_feedbacks')
    # ### end Alembic commands ###
