"""add_pairing_tokens_table

Revision ID: c74b06f80000
Revises: 08ea56170db1
Create Date: 2025-06-19 19:06:21.011231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c74b06f80000'
down_revision: Union[str, None] = '08ea56170db1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pairing_tokens',
    sa.Column('token_id', sa.Uuid(), nullable=False),
    sa.Column('therapist_id', sa.Uuid(), nullable=False),
    sa.Column('token_code', sqlmodel.sql.sqltypes.AutoString(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('used_by_client_id', sa.Uuid(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('current_uses', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['therapist_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['used_by_client_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('token_id'),
    sa.UniqueConstraint('token_code')
    )
    op.add_column('therapist_clients', sa.Column('pairing_source', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False))
    op.add_column('therapist_clients', sa.Column('pairing_token_id', sa.Uuid(), nullable=True))
    op.drop_index(op.f('ix_therapist_clients_client_id'), table_name='therapist_clients')
    op.drop_index(op.f('ix_therapist_clients_is_active'), table_name='therapist_clients')
    op.drop_index(op.f('ix_therapist_clients_therapist_id'), table_name='therapist_clients')
    op.create_foreign_key(None, 'therapist_clients', 'pairing_tokens', ['pairing_token_id'], ['token_id'])
    op.drop_index(op.f('ix_therapist_profiles_user_id'), table_name='therapist_profiles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_therapist_profiles_user_id'), 'therapist_profiles', ['user_id'], unique=False)
    op.drop_constraint(None, 'therapist_clients', type_='foreignkey')
    op.create_index(op.f('ix_therapist_clients_therapist_id'), 'therapist_clients', ['therapist_id'], unique=False)
    op.create_index(op.f('ix_therapist_clients_is_active'), 'therapist_clients', ['is_active'], unique=False)
    op.create_index(op.f('ix_therapist_clients_client_id'), 'therapist_clients', ['client_id'], unique=False)
    op.drop_column('therapist_clients', 'pairing_token_id')
    op.drop_column('therapist_clients', 'pairing_source')
    op.drop_table('pairing_tokens')
    # ### end Alembic commands ###
